name = "RegionTrees"
uuid = "dee08c22-ab7f-5625-9660-a9af2021b33f"
authors = ["Robin Deits <robin.deits@gmail.com>"]
repo = "https://github.com/rdeits/RegionTrees.jl"
version = "0.3.1"

[deps]
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Interpolations = "0.9, 0.10, 0.11, 0.12"
IterTools = "1"
StaticArrays = "0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11, 0.12, 1.0"
julia = "1"

[extras]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Test", "Interpolations"]
